import { Language } from './types';

export const FAMOUS_LEADERS = [
  "Winston Churchill", "Nelson Mandela", "Abraham Lincoln", "Sun Tzu",
  "Machiavelli", "Cleopatra", "Julius Caesar", "Catherine the Great",
  "Mahatma Gandhi", "Otto von Bismarck", "Napoleão Bonaparte", "Alexandre, o Grande"
];

export const TRANSLATIONS = {
  en: {
    title: "GeoDiplomacy",
    subtitle: "Global Relations Simulator",
    start: "Start Game",
    score: "Global Influence",
    selectCountry: "Select a country on the map to interact with",
    playerCountry: "Your Country",
    economic: "Economic",
    political: "Political",
    military: "Military",
    evaluating: "Analyzing diplomatic impact...",
    goodChoice: "Strategic Success",
    badChoice: "Diplomatic Setback",
    nextTurn: "Next Turn",
    changeLanguage: "Português",
    welcome: "Welcome, Leader",
    welcomeDesc: "You have been appointed to lead your nation. Your goal is to build strong international relations and increase your global influence.",
    pickCategory: "Choose the type of interaction",
    introTitle: "Your Nation Awaits",
    introDesc: "You have been chosen to lead:",
    beginDiplomacy: "Assume Office",
    confirmChoice: "Confirm Choice",
    cancel: "Cancel",
    autoRandom: "Auto-select next country",
    endGame: "Retire & View Legacy",
    gameOver: "End of Term",
    legacy: "Your Legacy",
    historicalMatch: "Historical Match",
    funMode: "Fun Mode: Compare Nations",
    selectCountryA: "Select First Country",
    selectCountryB: "Select Second Country",
    compare: "Analyze Compatibility",
    backToGame: "Back to Game",
    compatibilities: "Compatibilities",
    incompatibilities: "Incompatibilities",
    summary: "Summary",
    playAgain: "Play Again",
    analyzingLegacy: "Analyzing your legacy...",
    analyzingMatch: "Analyzing compatibility...",
    gameOverLowScore: "Your influence has fallen too low. Your government has collapsed.",
    bonusRound: "3x Bonus Round!",
    helpTools: "Lifelines (Once per game)",
    helpSocial: "What is social media saying?",
    helpAdvisors: "Government Advisors",
    helpLeader: "What would {leader} do?",
    consulting: "Consulting...",
    learnMore: "Learn more about {leader}",
  },
  pt: {
    title: "GeoDiplomacia",
    subtitle: "Simulador de Relações Globais",
    start: "Iniciar Jogo",
    score: "Influência Global",
    selectCountry: "Selecione um país no mapa para interagir",
    playerCountry: "Seu País",
    economic: "Econômico",
    political: "Político",
    military: "Militar",
    evaluating: "Analisando impacto diplomático...",
    goodChoice: "Sucesso Estratégico",
    badChoice: "Revés Diplomático",
    nextTurn: "Próximo Turno",
    changeLanguage: "English",
    welcome: "Bem-vindo, Líder",
    welcomeDesc: "Você foi nomeado para liderar sua nação. Seu objetivo é construir relações internacionais fortes e aumentar sua influência global.",
    pickCategory: "Escolha o tipo de interação",
    introTitle: "Sua Nação Aguarda",
    introDesc: "Você foi escolhido para liderar:",
    beginDiplomacy: "Assumir o Cargo",
    confirmChoice: "Confirmar Escolha",
    cancel: "Cancelar",
    autoRandom: "Auto-selecionar próximo país",
    endGame: "Aposentar & Ver Legado",
    gameOver: "Fim de Mandato",
    legacy: "Seu Legado",
    historicalMatch: "Correspondência Histórica",
    funMode: "Modo Diversão: Comparar Nações",
    selectCountryA: "Selecione o Primeiro País",
    selectCountryB: "Selecione o Segundo País",
    compare: "Analisar Compatibilidade",
    backToGame: "Voltar ao Jogo",
    compatibilities: "Compatibilidades",
    incompatibilities: "Incompatibilidades",
    summary: "Resumo",
    playAgain: "Jogar Novamente",
    analyzingLegacy: "Analisando seu legado...",
    analyzingMatch: "Analisando compatibilidade...",
    gameOverLowScore: "Sua influência caiu muito. Seu governo entrou em colapso.",
    bonusRound: "Rodada Bônus 3x!",
    helpTools: "Ajudas (Uma vez por jogo)",
    helpSocial: "O que as redes sociais estão dizendo?",
    helpAdvisors: "Conselheiros do governo",
    helpLeader: "O que faria {leader}?",
    consulting: "Consultando...",
    learnMore: "Conhecer mais sobre {leader}",
  }
};

export const CATEGORIES = ['Economic', 'Political', 'Military'] as const;
